From what I'm observing it seems to be a be associated with versions >=2.183.0. I solved by downgrading:

pip install sagemaker==2.182.0
